target_joint_name: "R_Ankle_FE"
contact_threshold: 30. # TODO (SH) : Need to be tuned
sleep_time: 0.8
b_measure_computation_time: true

service_call:
    conservative: true
    Neck_Pitch:
        kp: 15.
        kd: 0.
        current_limit: 0.15
        weak_kp: 15.
        weak_kd: 0.
        weak_current_limit: 0.05
    R_Hip_IE:
        kp: 150.
        kd: 1.
        current_limit: 0.3
        weak_kp: 150.
        weak_kd: 1.
        weak_current_limit: 0.1
    R_Hip_AA:
        kp: 400.
        kd: 3.
        current_limit: 0.6
        weak_kp: 400.
        weak_kd: 3.
        weak_current_limit: 0.2
    R_Hip_FE:
        kp: 500.
        kd: 5.
        current_limit: 0.7
        weak_kp: 500.
        weak_kd: 5.
        weak_current_limit: 0.2
    R_Knee_FE:
        kp: 250.
        kd: 1.5
        current_limit: 0.7
        weak_kp: 250.
        weak_kd: 1.5
        weak_current_limit: 0.1
    R_Ankle_FE:
        kp: 150.
        kd: 0.2
        current_limit: 0.3
        weak_kp: 150.
        weak_kd: 0.2
        weak_current_limit: 0.1
    R_Ankle_IE:
        kp: 30.
        kd: 0.1
        current_limit: 0.3
        weak_kp: 30.
        weak_kd: 0.1
        weak_current_limit: 0.1
    L_Hip_IE:
        kp: 150.
        kd: 1.
        current_limit: 0.3
        weak_kp: 150.
        weak_kd: 1.
        weak_current_limit: 0.1
    L_Hip_AA:
        kp: 400.
        kd: 3.
        current_limit: 0.6
        weak_kp: 400.
        weak_kd: 3.
        weak_current_limit: 0.2
    L_Hip_FE:
        kp: 500.
        kd: 5.
        current_limit: 0.7
        weak_kp: 500.
        weak_kd: 5.
        weak_current_limit: 0.2
    L_Knee_FE:
        kp: 250.
        kd: 1.5
        current_limit: 0.7
        weak_kp: 250.
        weak_kd: 1.5
        weak_current_limit: 0.1
    L_Ankle_FE:
        kp: 150.
        kd: 0.2
        current_limit: 0.3
        weak_kp: 150.
        weak_kd: 0.2
        weak_current_limit: 0.1
    L_Ankle_IE:
        kp: 30.
        kd: 0.1
        current_limit: 0.3
        weak_kp: 30.
        weak_kd: 0.1
        weak_current_limit: 0.1
    L_Shoulder_FE:
        kp: 250.
        kd: 3.
        current_limit: 0.7
        weak_kp: 250.
        weak_kd: 5.
        weak_current_limit: 0.2
    L_Shoulder_AA:
        kp: 300.
        kd: 3.
        current_limit: 0.65
        weak_kp: 300.
        weak_kd: 3.
        weak_current_limit: 0.2
    L_Shoulder_IE:
        kp: 60.
        kd: 2.
        current_limit: 0.3
        weak_kp: 60.
        weak_kd: 2.
        weak_current_limit: 0.2
    L_Elbow:
        kp: 100.
        kd: 1.2
        current_limit: 0.3
        weak_kp: 100.
        weak_kd: 1.2
        weak_current_limit: 0.2
    L_Wrist_Roll:
        kp: 15.
        kd: 1.
        current_limit: 0.2
        weak_kp: 15.
        weak_kd: 1.
        weak_current_limit: 0.06
    L_Wrist_Pitch:
        kp: 7.0
        kd: 0.07
        current_limit: 0.1
        weak_kp: 7.0
        weak_kd: 0.07
        weak_current_limit: 0.03
    R_Shoulder_FE:
        kp: 250.
        kd: 3.
        current_limit: 0.7
        weak_kp: 250.
        weak_kd: 5.
        weak_current_limit: 0.2
    R_Shoulder_AA:
        kp: 300.
        kd: 3.
        current_limit: 0.65
        weak_kp: 300.
        weak_kd: 3.
        weak_current_limit: 0.2
    R_Shoulder_IE:
        kp: 60.
        kd: 2.
        current_limit: 0.3
        weak_kp: 60.
        weak_kd: 2.
        weak_current_limit: 0.1
    R_Elbow:
        kp: 100.
        kd: 1.2
        current_limit: 0.3
        weak_kp: 100.
        weak_kd: 1.2
        weak_current_limit: 0.1
    R_Wrist_Roll:
        kp: 15.
        kd: 1.
        current_limit: 0.2
        weak_kp: 15.
        weak_kd: 1.
        weak_current_limit: 0.06
    R_Wrist_Pitch:
        kp: 7.0
        kd: 0.07
        current_limit: 0.1
        weak_kp: 7.0
        weak_kd: 0.07
        weak_current_limit: 0.03

